# Generated by Django 5.2.10 on 2026-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_image_customuser_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Referral ID'),
        ),
    ]
