# Generated by Django 5.2.10 on 2026-01-20 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('features', 'Features Section'), ('plans', 'Income Plans'), ('products', 'Products Section'), ('testimonials', 'Testimonials'), ('faq', 'FAQ Section')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Section',
                'verbose_name_plural': 'Home Page Sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_referral_amount', models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='Direct Referral Amount (₹)')),
                ('matching_income_percentage', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Matching Income Percentage (%)')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Settings',
                'verbose_name_plural': 'Referral Settings',
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='👥', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.CharField(help_text='Can be percentage, amount, or symbol', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='core.homepagesection')),
            ],
            options={
                'verbose_name': 'Plan Item',
                'verbose_name_plural': 'Plan Items',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='core.homepagesection')),
            ],
            options={
                'verbose_name': 'Home Page Product',
                'verbose_name_plural': 'Home Page Products',
                'ordering': ['display_order'],
            },
        ),
    ]
