# Generated by Django 5.2.10 on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepagesection_referralsettings_planitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]

